services:
  fiesta-db:
    image: postgres:latest
    container_name: expert-fiesta-postgres
    restart: always
    environment:
      POSTGRES_USER: fiesta_admin
      POSTGRES_PASSWORD: fiesta_admin_password
      POSTGRES_DB: expert_fiesta
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql